## 1) data preprocessing

In [151]:
import pandas as pd
import numpy as np

NL = pd.read_csv(r"C:\Users\joris\Documents\Python course EFDS\EfDS_assignments\assignment_C\data\NL.csv")
PL = pd.read_csv(r"C:\Users\joris\Documents\Python course EFDS\EfDS_assignments\assignment_C\data\PL.csv")
UK = pd.read_csv(r"C:\Users\joris\Documents\Python course EFDS\EfDS_assignments\assignment_C\data\UK.csv")
US = pd.read_csv(r"C:\Users\joris\Documents\Python course EFDS\EfDS_assignments\assignment_C\data\US.csv")
genes = pd.read_csv(r"C:\Users\joris\Documents\Python course EFDS\EfDS_assignments\assignment_C\data\genes.csv")

In [152]:
print(NL)
NL.keys() 

print(f"\nI want to check if all the data in height and weight is logical and if there are wrong outliers.")
print(f"the maximum weight is: {max(NL["weight"])}") # now i want to check if all the data in height and weight is logical. There shouldnt be data above 300 cm or weight above 250 kg
print(f"the minimum weight is: {min(NL["weight"])}")
print(f"the maximum height is: {max(NL["height"])}")
print(f"the minimum height is: {min(NL["height"])}")

print(f"\nAlso, I want to see if there are nan values and i want to see info about the data using info and describe")
print(NL["sex"].unique())
print(NL["smokes"].unique())
print(NL.info())
print(NL.describe())

print(f"\nConclusion: no nan data or weird outliers in the dataset. The data looks clean and logical to me.")

           id  weight  height     sex smokes
0     NL_0001     105     188    male    yes
1     NL_0002     114     177    male    yes
2     NL_0003      70     176  female     no
3     NL_0004      68     175    male     no
4     NL_0005      86     186    male    yes
...       ...     ...     ...     ...    ...
1317  NL_1318      48     168  female     no
1318  NL_1319      97     181    male     no
1319  NL_1320      96     185    male     no
1320  NL_1321      77     176  female     no
1321  NL_1322      71     168  female    yes

[1322 rows x 5 columns]

I want to check if all the data in height and weight is logical and if there are wrong outliers.
the maximum weight is: 142
the minimum weight is: 35
the maximum height is: 207
the minimum height is: 153

Also, I want to see if there are nan values and i want to see info about the data using info and describe
<StringArray>
['male', 'female']
Length: 2, dtype: str
<StringArray>
['yes', 'no']
Length: 2, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 1322 entries, 0 to 1321
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1322 non-null   str
 1   weight  1322 non-null   int64
 2   height  1322 non-null   int64
 3   sex     1322 non-null   str
 4   smokes  1322 non-null   str
dtypes: int64(2), str(3)
memory usage: 51.8 KB
None
            weight       height
count  1322.000000  1322.000000
mean     80.231467   177.176248
std      16.460242     9.276962
min      35.000000   153.000000
25%      69.000000   170.000000
50%      79.500000   176.500000
75%      91.750000   184.000000
max     142.000000   207.000000

Conclusion: no nan data or weird outliers in the dataset. The data looks clean and logical to me.

In [153]:
print(f"I will only add one column 'country' to the NL table (and all other datasets) so I can easily analyse later on on country.")
NL_changed = NL.copy()
NL_changed["country"] = "NL"
NL_changed

I will only add one column 'country' to the NL table (and all other datasets) so I can easily analyse later on on country.

           id  weight  height     sex smokes country
0     NL_0001     105     188    male    yes      NL
1     NL_0002     114     177    male    yes      NL
2     NL_0003      70     176  female     no      NL
3     NL_0004      68     175    male     no      NL
4     NL_0005      86     186    male    yes      NL
...       ...     ...     ...     ...    ...     ...
1317  NL_1318      48     168  female     no      NL
1318  NL_1319      97     181    male     no      NL
1319  NL_1320      96     185    male     no      NL
1320  NL_1321      77     176  female     no      NL
1321  NL_1322      71     168  female    yes      NL

[1322 rows x 6 columns]

In [154]:
print(PL)
PL.keys()

print(f"the maximum weight is: {max(PL["weight"])}") # now i want to check if all the data in height and weight is logical. There shouldnt be data above 300 cm or weight above 250 kg
print(f"the minimum weight is: {min(PL["weight"])}")
print(f"the maximum height is: {max(PL["heigth"])}")
print(f"the minimum height is: {min(PL["heigth"])}")
print(PL["sex"].unique())
print(PL["smokes"].unique())
print(PL.info())
print(PL.describe())

         id  heigth  weight     sex smokes
0     S0001   178.0    77.0  female  False
1     S0002   155.0    74.0    male  False
2     S0003   173.0    70.0    male   True
3     S0004   167.0    95.0    male  False
4     S0005   181.0    78.0  female  False
...     ...     ...     ...     ...    ...
1533  S0537   158.0    56.0    male  False
1534  S0538   159.0    43.0    male  False
1535  S0539   162.0    80.0    male  False
1536  S053a   194.0   110.0     NaN   True
1537  S053b   172.0    67.0    male  False

[1538 rows x 5 columns]
the maximum weight is: 149.0
the minimum weight is: 35.0
the maximum height is: 202.0
the minimum height is: 146.0
<StringArray>
['female', 'male', nan]
Length: 3, dtype: str
[False True nan]
<class 'pandas.DataFrame'>
RangeIndex: 1538 entries, 0 to 1537
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1538 non-null   str
 1   heigth  1472 non-null   float64
 2   weight  1494 non-null   float64
 3   sex     1504 non-null   str
 4   smokes  1434 non-null   object
dtypes: float64(2), object(1), str(2)
memory usage: 60.2+ KB
None
            heigth       weight
count  1472.000000  1494.000000
mean    169.404891    75.417001
std       9.580837    16.261988
min     146.000000    35.000000
25%     161.000000    65.000000
50%     168.000000    72.000000
75%     176.000000    86.000000
max     202.000000   149.000000

In [155]:
print(f"Adjustments I will make to the PL dataset, based on the information:")
print(f"-Height and weight have one decimal. I will changed it from floating to integer to be consistent with NL dataset.")
print(f"-There are empty values in column sex. I want them removed, also from all other columns that contain NaN values. Apart from smokes column. There i will change the value to unknown")
print(f"-Smokes column should be changed to yes/no instead of true/false to be consistent with NL dataset")
print(f"-The column name heigth is wrongly called heigth. I will change it to height")

Adjustments I will make to the PL dataset, based on the information:
-Height and weight have one decimal. I will changed it from floating to integer to be consistent with NL dataset.
-There are empty values in column sex. I want them removed, also from all other columns that contain NaN values. Apart from smokes column. There i will change the value to unknown
-Smokes column should be changed to yes/no instead of true/false to be consistent with NL dataset
-The column name heigth is wrongly called heigth. I will change it to height

In [156]:
PL_changed = PL.copy() # I made a copy of the dataframe. I will change/update this one below

PL_changed["smokes"] = PL_changed["smokes"].fillna("Unknown")
PL_changed = PL_changed.dropna(axis=0)
PL_changed = PL_changed.rename(columns={"heigth": "height"})
PL_changed.loc[PL_changed["smokes"] == False, "smokes"] = "no"
PL_changed.loc[PL_changed["smokes"] == True, "smokes"] = "yes"
PL_changed["height"] = PL_changed["height"].astype(int)
PL_changed["weight"] = PL_changed["weight"].astype(int)
PL_changed["country"] = "PL"

PL_changed

         id  height  weight     sex smokes country
0     S0001     178      77  female     no      PL
1     S0002     155      74    male     no      PL
2     S0003     173      70    male    yes      PL
3     S0004     167      95    male     no      PL
4     S0005     181      78  female     no      PL
...     ...     ...     ...     ...    ...     ...
1532  S0536     167      86    male    yes      PL
1533  S0537     158      56    male     no      PL
1534  S0538     159      43    male     no      PL
1535  S0539     162      80    male     no      PL
1537  S053b     172      67    male     no      PL

[1397 rows x 6 columns]

In [157]:
print(UK)
UK.keys()
print(f"the maximum weight is: {max(UK["weight"])}") # now i want to check if all the data in height and weight is logical. There shouldnt be data above 300 cm or weight above 250 kg
print(f"the minimum weight is: {min(UK["weight"])}")
print(f"the maximum height is: {max(UK["height"])}")
print(f"the minimum height is: {min(UK["height"])}")
print(UK["sex"].unique())
print(UK["smokes"].unique())
print(UK.info())
print(UK.describe())

          id  weight  height     sex  smokes
0    UK_0001   180.8    -1.0    male       0
1    UK_0002   141.1    65.7    male       0
2    UK_0003   180.8    68.5    male       0
3    UK_0004   218.3    68.9    male       0
4    UK_0005   147.7    62.6  female       0
..       ...     ...     ...     ...     ...
689  UK_0690   156.5    61.8  female       0
690  UK_0691   176.4    65.4    male       1
691  UK_0692   205.0    72.4    male       0
692  UK_0693   130.1    66.1  female       0
693  UK_0694   114.6    63.4  female       0

[694 rows x 5 columns]
the maximum weight is: 999.0
the minimum weight is: 61.7
the maximum height is: 78.0
the minimum height is: -1.0
<StringArray>
['male', 'female', 'FEMALE', 'Woman', 'Male', 'MALE', 'Female']
Length: 7, dtype: str
[0 1]
<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      694 non-null    str
 1   weight  694 non-null    float64
 2   height  694 non-null    float64
 3   sex     694 non-null    str
 4   smokes  694 non-null    int64
dtypes: float64(2), int64(1), str(2)
memory usage: 27.2 KB
None
           weight      height      smokes
count  694.000000  694.000000  694.000000
mean   273.200865   64.406484    0.145533
std    264.109384   14.566331    0.352892
min     61.700000   -1.000000    0.000000
25%    158.700000   64.600000    0.000000
50%    185.200000   67.300000    0.000000
75%    211.600000   69.700000    0.000000
max    999.000000   78.000000    1.000000

In [158]:
print(f"I will change the following things in the UK dataset to harmonize and clean the data:")
print(f"-change the 0 and 1 values in the smokes column to yes and no")
print(f"-harmonize all the values in the sex column to only female or male")
print(f"-the column name height should be weight and vice versa, considering the data values. I will change this")
print(f"-I will make the values of height and weight integers, just like in the NL data")
print(f"-Any values that don't make sense in height and weight, I will exclude. So if weight is lower than 25 kg or higher than 650. This is simply not possible.")
print(f"-Also height higher than 300 and lower than 50 (like -1) i will discard")
UK_changed = UK.copy()

UK_changed = UK_changed.dropna(axis=0)
UK_changed["smokes"] = UK_changed["smokes"].astype(str)
UK_changed.loc[UK_changed["smokes"] == "0", "smokes"] = "no" # assuming 0 is equal to "no"
UK_changed.loc[UK_changed["smokes"] == "1", "smokes"] = "yes"

UK_changed.loc[UK_changed["sex"] == "FEMALE", "sex"] = "female"
UK_changed.loc[UK_changed["sex"] == "Woman", "sex"] = "female"
UK_changed.loc[UK_changed["sex"] == "Male", "sex"] = "male"
UK_changed.loc[UK_changed["sex"] == "MALE", "sex"] = "male"
UK_changed.loc[UK_changed["sex"] == "Female", "sex"] = "female"

UK_changed = UK_changed.rename(columns={"height": "weight1"})
UK_changed = UK_changed.rename(columns={"weight": "height"})
UK_changed = UK_changed.rename(columns={"weight1": "weight"})

UK_changed["height"] = UK_changed["height"].astype(int)
UK_changed["weight"] = UK_changed["weight"].astype(int)

UK_changed = UK_changed[(UK_changed["weight"] < 650) & (UK_changed["weight"] > 25) & (UK_changed["height"] > 50) & (UK_changed["height"] < 300)]

UK_changed["country"] = "UK"
UK_changed

I will change the following things in the UK dataset to harmonize and clean the data:
-change the 0 and 1 values in the smokes column to yes and no
-harmonize all the values in the sex column to only female or male
-the column name height should be weight and vice versa, considering the data values. I will change this
-I will make the values of height and weight integers, just like in the NL data
-Any values that don't make sense in height and weight, I will exclude. So if weight is lower than 25 kg or higher than 650. This is simply not possible.
-Also height higher than 300 and lower than 50 (like -1) i will discard

          id  height  weight     sex smokes country
1    UK_0002     141      65    male     no      UK
2    UK_0003     180      68    male     no      UK
3    UK_0004     218      68    male     no      UK
4    UK_0005     147      62  female     no      UK
5    UK_0006     216      68    male     no      UK
..       ...     ...     ...     ...    ...     ...
689  UK_0690     156      61  female     no      UK
690  UK_0691     176      65    male    yes      UK
691  UK_0692     205      72    male     no      UK
692  UK_0693     130      66  female     no      UK
693  UK_0694     114      63  female     no      UK

[586 rows x 6 columns]

In [159]:
print(US)
US.keys()
print(f"the maximum weight is: {max(US["weight"])}")
print(f"the minimum weight is: {min(US["weight"])}")
print(f"the maximum height is: {max(US["height"])}")
print(f"the minimum height is: {min(US["height"])}")
print(US["sex"].unique())
print(US["smokes"].unique())
print(US.info())
print(US.describe())

        id  weight  height     sex smokes
0    S1272      61     NaN  female     no
1    S1288     105     NaN  female     no
2    S1361      92     NaN  female     no
3    S1091      78   182.0    male     no
4    S1351      83     NaN  female     no
..     ...     ...     ...     ...    ...
456  S1300      61     NaN  female     no
457  S1169     112   179.0    male     no
458  S1048      96   172.0    male    yes
459  S1352      62     NaN  female     no
460  S1207      70   169.0    male     no

[461 rows x 5 columns]
the maximum weight is: 138
the minimum weight is: 40
the maximum height is: nan
the minimum height is: nan
<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['no', 'yes']
Length: 2, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 461 entries, 0 to 460
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      461 non-null    str
 1   weight  461 non-null    int64
 2   height  226 non-null    float64
 3   sex     461 non-null    str
 4   smokes  461 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 18.1 KB
None
           weight      height
count  461.000000  226.000000
mean    81.754881  174.566372
std     16.541733    6.892026
min     40.000000  157.000000
25%     70.000000  170.000000
50%     81.000000  174.000000
75%     93.000000  179.000000
max    138.000000  198.000000

In [160]:
print(f"I will change the following things in the US dataset to harmonize and clean the data:")
print(f"-I will drop all the NaN values, given they are not in the columngs sex and smokes")
print(f"-The column height becomes integer values")

US_changed = US.copy()

US_changed = US_changed.dropna(axis=0)
US_changed["country"] = "US"
US_changed["height"] = US_changed["height"].astype(int)

print(f"\nThe maximum weight after dropping nan values is: {max(US_changed["weight"])}")
print(f"The minimum weight after dropping nan values is: {min(US_changed["weight"])}")
print(f"The maximum height after dropping nan values is: {max(US_changed["height"])}")
print(f"The minimum height after dropping nan values is: {min(US_changed["height"])}")

US_changed

I will change the following things in the US dataset to harmonize and clean the data:
-I will drop all the NaN values, given they are not in the columngs sex and smokes
-The column height becomes integer values

The maximum weight after dropping nan values is: 132
The minimum weight after dropping nan values is: 58
The maximum height after dropping nan values is: 198
The minimum height after dropping nan values is: 157

        id  weight  height   sex smokes country
3    S1091      78     182  male     no      US
9    S1063      88     173  male     no      US
10   S1067      84     178  male     no      US
11   S1181      89     167  male     no      US
12   S1140      83     165  male     no      US
..     ...     ...     ...   ...    ...     ...
451  S1171      97     173  male     no      US
452  S1123      83     172  male     no      US
457  S1169     112     179  male     no      US
458  S1048      96     172  male    yes      US
460  S1207      70     169  male     no      US

[226 rows x 6 columns]

In [161]:
print(f"I will combine the four changed datasets and add the bmi formula to the data: bmi = weight (kg) / (height in meter * height in meter)")

countries_comb = pd.concat([NL_changed, PL_changed, UK_changed, US_changed])

countries_comb["bmi"] = countries_comb["weight"] / ( (countries_comb["height"]/100)*(countries_comb["height"]/100) )

countries_comb = countries_comb.round({"bmi": 2})
countries_comb

I will combine the four changed datasets and add the bmi formula to the data: bmi = weight (kg) / (height in meter * height in meter)

          id  weight  height     sex smokes country    bmi
0    NL_0001     105     188    male    yes      NL  29.71
1    NL_0002     114     177    male    yes      NL  36.39
2    NL_0003      70     176  female     no      NL  22.60
3    NL_0004      68     175    male     no      NL  22.20
4    NL_0005      86     186    male    yes      NL  24.86
..       ...     ...     ...     ...    ...     ...    ...
451    S1171      97     173    male     no      US  32.41
452    S1123      83     172    male     no      US  28.06
457    S1169     112     179    male     no      US  34.96
458    S1048      96     172    male    yes      US  32.45
460    S1207      70     169    male     no      US  24.51

[3531 rows x 7 columns]

In [162]:
print(countries_comb)
countries_comb.keys()

print(f"The maximum weight is: {max(countries_comb["weight"])}")
print(f"The minimum weight is: {min(countries_comb["weight"])}")
print(f"The maximum height is: {max(countries_comb["height"])}")
print(f"The minimum height is: {min(countries_comb["height"])}")
print(countries_comb["sex"].unique())
print(countries_comb["smokes"].unique())
print(countries_comb["country"].unique())
print(countries_comb.info())
print(countries_comb.describe())

          id  weight  height     sex smokes country    bmi
0    NL_0001     105     188    male    yes      NL  29.71
1    NL_0002     114     177    male    yes      NL  36.39
2    NL_0003      70     176  female     no      NL  22.60
3    NL_0004      68     175    male     no      NL  22.20
4    NL_0005      86     186    male    yes      NL  24.86
..       ...     ...     ...     ...    ...     ...    ...
451    S1171      97     173    male     no      US  32.41
452    S1123      83     172    male     no      US  28.06
457    S1169     112     179    male     no      US  34.96
458    S1048      96     172    male    yes      US  32.45
460    S1207      70     169    male     no      US  24.51

[3531 rows x 7 columns]
The maximum weight is: 142
The minimum weight is: 35
The maximum height is: 284
The minimum height is: 61
<StringArray>
['male', 'female']
Length: 2, dtype: str
['yes' 'no' 'Unknown']
<StringArray>
['NL', 'PL', 'UK', 'US']
Length: 4, dtype: str
<class 'pandas.DataFrame'>
Index: 3531 entries, 0 to 460
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3531 non-null   str
 1   weight   3531 non-null   int64
 2   height   3531 non-null   int64
 3   sex      3531 non-null   str
 4   smokes   3531 non-null   object
 5   country  3531 non-null   str
 6   bmi      3531 non-null   float64
dtypes: float64(1), int64(2), object(1), str(3)
memory usage: 220.7+ KB
None
            weight       height          bmi
count  3531.000000  3531.000000  3531.000000
mean     76.299349   173.867743    25.615163
std      15.594749    16.600908     6.252406
min      35.000000    61.000000     8.930000
25%      65.000000   165.000000    22.310000
50%      73.000000   173.000000    25.180000
75%      86.000000   182.000000    28.690000
max     142.000000   284.000000   163.930000

In [163]:
print(genes)
genes.keys() 

print(genes.info())
print(genes.describe())
print(genes["source"].unique())

           id source      geneA      geneB       geneC
0     NL_0590     NL   0.725787  10.516221   88.803319
1     NL_0395     NL   1.827190  -1.364823  100.720557
2     NL_0183     NL   2.701437  14.623456   89.894749
3     NL_0308     NL   1.729680  10.100416   99.305338
4     NL_0826     NL   0.470720  -3.894969  103.650732
...       ...    ...        ...        ...         ...
3492    S1406     US   1.129991   8.910793   98.230566
3493    S1221     US   1.688210   7.187131  112.130364
3494    S1218     US   1.084599  -3.339440  121.564776
3495    S1306     US  27.838815  22.259590   93.332950
3496    S1293     US   0.945320   0.947765  112.300317

[3497 rows x 5 columns]
<class 'pandas.DataFrame'>
RangeIndex: 3497 entries, 0 to 3496
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3497 non-null   str
 1   source  3497 non-null   str
 2   geneA   3497 non-null   float64
 3   geneB   3497 non-null   float64
 4   geneC   3497 non-null   float64
dtypes: float64(3), str(2)
memory usage: 136.7 KB
None
             geneA        geneB        geneC
count  3497.000000  3497.000000  3497.000000
mean      1.809871    -0.162271   100.050480
std       2.683657    12.144372    10.175763
min       0.011660   -42.924768    61.546798
25%       0.481570    -8.681027    93.030443
50%       1.009108    -0.130598   100.098050
75%       1.979031     7.864601   106.901907
max      41.190790    43.533614   138.477677
<StringArray>
['NL', 'GB', 'PL', 'US']
Length: 4, dtype: str

In [164]:
merged_genes_country = pd.merge(countries_comb, genes, on="id")
merged_genes_country

,id,weight,height,sex,smokes,country,bmi,source,geneA,geneB,geneC
0,NL_0001,105,188,male,yes,NL,29.71,NL,2.852573,15.139682,88.698757
1,NL_0002,114,177,male,yes,NL,36.39,NL,23.406720,23.477106,105.267242
2,NL_0003,70,176,female,no,NL,22.60,NL,0.375769,-6.081572,99.667734
3,NL_0004,68,175,male,no,NL,22.20,NL,0.800761,-10.197789,82.935411
4,NL_0005,86,186,male,yes,NL,24.86,NL,1.008053,2.101691,97.957148
...,...,...,...,...,...,...,...,...,...,...,...
3367,S1149,95,190,male,no,US,26.32,US,0.471653,-10.102222,109.661893
3368,S1204,90,179,male,no,US,28.09,US,0.741639,-2.726620,107.903716
3369,S1075,74,170,male,yes,US,25.61,US,0.490165,-14.369042,99.951556
3370,S1171,97,173,male,no,US,32.41,US,2.144371,11.210542,93.698942
3371,S1207,70,169,male,no,US,24.51,US,0.340582,-10.489534,99.154091

In [165]:
print(f"Now i will check whether the merge gave any problems\n")

print(merged_genes_country.info())
print(merged_genes_country.describe())

print(max(merged_genes_country["weight"]))
print(min(merged_genes_country["weight"]))
print(max(merged_genes_country["height"]))
print(min(merged_genes_country["height"]))

print(max(merged_genes_country["geneA"]))
print(min(merged_genes_country["geneA"]))

print(max(merged_genes_country["geneB"]))
print(min(merged_genes_country["geneB"]))

print(max(merged_genes_country["geneC"]))
print(min(merged_genes_country["geneC"]))

# Also, I want to see if there are nan values and i want to see info about the data using info and describe
print(merged_genes_country["sex"].unique())
print(merged_genes_country["smokes"].unique())

Now i will check whether the merge gave any problems

<class 'pandas.DataFrame'>
RangeIndex: 3372 entries, 0 to 3371
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3372 non-null   str
 1   weight   3372 non-null   int64
 2   height   3372 non-null   int64
 3   sex      3372 non-null   str
 4   smokes   3372 non-null   object
 5   country  3372 non-null   str
 6   bmi      3372 non-null   float64
 7   source   3372 non-null   str
 8   geneA    3372 non-null   float64
 9   geneB    3372 non-null   float64
 10  geneC    3372 non-null   float64
dtypes: float64(4), int64(2), object(1), str(4)
memory usage: 289.9+ KB
None

            weight       height          bmi        geneA        geneB  \
count  3372.000000  3372.000000  3372.000000  3372.000000  3372.000000
mean     75.731317   173.843713    25.454994     1.753893    -0.349075
std      15.395667    16.923709     6.284697     2.584424    11.759838
min      35.000000    61.000000     8.930000     0.011660   -42.924768
25%      65.000000   164.000000    22.147500     0.511676    -8.015268
50%      72.000000   173.000000    25.080000     1.085848    -1.104572
75%      85.250000   182.000000    28.410000     1.884964     7.285008
max     142.000000   284.000000   163.930000    41.190790    43.533614

             geneC
count  3372.000000
mean     98.809430
std      11.006897
min      61.546798
25%      91.420504
50%      99.257662
75%     106.349215
max     138.477677
142
35
284
61
41.19079018461634
0.0116598122580536
43.53361352363809
-42.924768037350994
138.4776770582989
61.546798305399626
<StringArray>
['male', 'female']
Length: 2, dtype: str
['yes' 'no' 'Unknown']

In [166]:
print(f"I found on the internet which bmi is considered to be underweight, healthy, overweight, or obesitas class 1, 2 or 3. This is interesting information for the analyses, so I create a function")
def bmi_category(value):

    if value < 18.5:
        return "underweight"
    
    elif value < 25:
        return "healthy"
    
    elif value < 30:
        return "overweight"
    
    elif value < 35:
        return "obesity_class_1"
    
    elif value < 40:
        return "obesity_class_2"
    
    else:
        return "obesity_class_3"

I found on the internet which bmi is considered to be underweight, healthy, overweight, or obesitas class 1, 2 or 3. This is interesting information for the analyses, so I create a function

In [167]:
print(f"I will apply the function to bmi column and create a new column called bmi_category with the results\n")

merged_genes_country["bmi_category"] = merged_genes_country["bmi"].apply(bmi_category)
print(merged_genes_country)

I will apply the function to bmi column and create a new column called bmi_category with the results

           id  weight  height     sex smokes country    bmi source      geneA  \
0     NL_0001     105     188    male    yes      NL  29.71     NL   2.852573
1     NL_0002     114     177    male    yes      NL  36.39     NL  23.406720
2     NL_0003      70     176  female     no      NL  22.60     NL   0.375769
3     NL_0004      68     175    male     no      NL  22.20     NL   0.800761
4     NL_0005      86     186    male    yes      NL  24.86     NL   1.008053
...       ...     ...     ...     ...    ...     ...    ...    ...        ...
3367    S1149      95     190    male     no      US  26.32     US   0.471653
3368    S1204      90     179    male     no      US  28.09     US   0.741639
3369    S1075      74     170    male    yes      US  25.61     US   0.490165
3370    S1171      97     173    male     no      US  32.41     US   2.144371
3371    S1207      70     169    male     no      US  24.51     US   0.340582

          geneB       geneC     bmi_category
0     15.139682   88.698757       overweight
1     23.477106  105.267242  obesity_class_2
2     -6.081572   99.667734          healthy
3    -10.197789   82.935411          healthy
4      2.101691   97.957148          healthy
...         ...         ...              ...
3367 -10.102222  109.661893       overweight
3368  -2.726620  107.903716       overweight
3369 -14.369042   99.951556       overweight
3370  11.210542   93.698942  obesity_class_1
3371 -10.489534   99.154091          healthy

[3372 rows x 12 columns]

In [168]:
merged_genes_country.to_csv("merged_dataset.csv",index=False)